### ISSUE TITLE
Godot keeps closing

### ISSUE THREAD

**Issue by nemui3353** [acedogblast/Project-Uranium-Godot#1]
I followed all the Setup and Building Instructions until step 8.
And when I open the project file(double clicked it on godot)
It crashed without any dialog or warning.
So I can't even edit this project.
How could I fix this?

**Comment by 5H4D0WILA** [comment]
What operating system are you using?
Also, which specs do you have?

**Comment by acedogblast** [comment]
I know what is going on. Some of the assets in Uranium are broken and will lead to godot crashing. See the "Fixing Assets" part.

**Comment by acedogblast** [comment]
Also this part is very confusing and difficult I plan to release a program that will do this whole this for you.

**Comment by ShadowTheReal** [comment]
But if he is at step 8 he should have fixed the assets already

**Comment by nemui3353** [comment]
On latest version there's no issue with build.
Thanks!
Thread closed
