### ISSUE TITLE
Dialogue is looping Choose.ogg

### ISSUE THREAD

**Issue by dylmeadows** [acedogblast/Project-Uranium-Godot#14]
On a clean checkout of the project, the AudioStreamPlayer in the DialogueBox is looping the "choose" sound indefinitely. I was able to produce this by selecting "New Game". Whenever the `_ready` function is called, the looping begins.

**Comment by acedogblast** [comment]
Fixed. The AudioStreamPlayer was using the ogg version of choose instead of the wav which was causing the looping.
