### ISSUE TITLE
Crash on first story cutscene

### ISSUE THREAD

**Issue by acedogblast** [acedogblast/Project-Uranium-Godot#16]
The game crashes on the first story cutscene when skipping text as fast as possible.

**Comment by acedogblast** [comment]
Error when crash occurs: Invalid get index '2' (on base: 'PoolStringArray')
occurs on line 78 of the 'Dialogue Box' scene.

**Comment by Ev1lbl0w** [comment]
I've had that crash only once and I though a `yield` fixed it. I'll investigate it then.

**Comment by Ev1lbl0w** [comment]
From my experiments, it seems to happen only on single-line text. I'll look further into it.
