### ISSUE TITLE
Dialogue Box not visible on Player Creation with bambo.

### ISSUE THREAD

**Issue by acedogblast** [acedogblast/Project-Uranium-Godot#37]
The Dialogue Box is not visible on Player Creation with Bambo but works fine everywhere else.

**Comment by Ev1lbl0w** [comment]
So by "everywhere else", does it mean it works on normal gameplay? *(moki town, for example)*

**Comment by acedogblast** [comment]
Haven't tried moki town due to another bug but from from what I could test I was everything else up to spawning in moki town.
