### ISSUE TITLE
References to *-Resized.png assets that are not present in the original game

### ISSUE THREAD

**Issue by lboklin** [acedogblast/Project-Uranium-Godot#51]
symlinking to the correspondingly named non-resized results in oddly sized textures, as could be expected.

List of files:
```
Graphics/Tilesets/Indoor-Resized.png
Graphics/Tilesets/PU-NuclearPlantInside-Resized.png
Graphics/Tilesets/PU-Route01-02-Moki-Kevlar-Resized.png
Graphics/Tilesets/PU-Route01-02-Moki-Kevlar-Resized.png
Graphics/Tilesets/PU-Route03-Comet-Resized.png
```

**Comment by acedogblast** [comment]
These resized files are created by the auto-builder. The original assets are not optimized for use in Godot since they had their pixels "quadrupled" or having 4 pixels the same as just one. The tileset textures where also arranged in a long vertical strip.
