### ISSUE TITLE
There seems to be a lack of some image resources？

### ISSUE THREAD

**Issue by colorworlds** [acedogblast/Project-Uranium-Godot#59]
I want to study this project, but when I download the project and run it, I will be prompted for lack of resources.
for example;
res://Graphics/Pictures/Arrow1.png
Why is the **Graphics** folder missing? I can't find this folder. What should I do? thank you for any advice.

**Comment by acedogblast** [comment]
Please follow the setup instructions. Here: [https://github.com/acedogblast/Project-Uranium-Godot/wiki/Setup-and-Building-Instructions](https://github.com/acedogblast/Project-Uranium-Godot/wiki/Setup-and-Building-Instructions)

**Comment by colorworlds** [comment]
> Please follow the setup instructions. Here: https://github.com/acedogblast/Project-Uranium-Godot/wiki/Setup-and-Building-Instructions

I imported the original files of the Uranium  into the project. Some scene can be run, but some dependencies need to be modified. Although it is a little slow, it is works. Thank you very much for your help!
