### ISSUE TITLE
Transition flips back and forth when going downstairs in HeroHome.tscn

### ISSUE THREAD

**Issue by godofgrunts** [acedogblast/Project-Uranium-Godot#8]
I believe the issue is caused by the `CollisionShape2D` being rapidly set to `true` and `false` in `_process`

**Comment by 5H4D0WILA** [comment]
no, its because the movement gets done everytime, even tho you shouldnt be there anymore

**Comment by 5H4D0WILA** [comment]
This is btw fixed
